username: ''
password: ''
addr: [ 172.28.0.1:19094 ]
toRedis:
  topic: "toRedis"
toMongo:
  topic: "toMongo"
toPush:
  topic: "toPush"
consumerGroupID:
  msgToRedis: redis
  msgToMongo: mongo
  msgToPush: push
