rpc:
  registerIP: ''
  listenIP: 0.0.0.0
rpcPort:
  openImUserPort: [ 10110 ]
rpcRegisterName:
  openImUserName: User

prometheus:
  enable: true
  grafanaUrl: http://127.0.0.1:13000/
  prometheusPort: [ 20110 ]

