rpc:
  registerIP: ''
  listenIP: 0.0.0.0
  ports: [ 10130 ]

prometheus:
  enable: true
  ports: [20130]



messageVerify:
  friendVerify: false

  groupMessageHasReadReceiptEnable: true

  singleMessageHasReadReceiptEnable: true

