# openim.yaml 作为存放一些通用配置或特殊配置的文件，我们将包含日志、消息缓存、多登录策略、消息验证策略等配置。
# 这些配置是跨多个服务的共享配置，它们对于整个系统的运行至关重要。
log:
  storageLocation: /data/workspaces/open-im-server/_output/logs/
  rotationTime: 24
  remainRotationCount: 2
  remainLogLevel: 6
  isStdout: false
  isJson: false
  withStack: false

msgCacheTimeout: 86400





tokenPolicy:
  expire: 90







secret: openIM123




