rpc:
  registerIP: ''
  listenIP: 0.0.0.0
  ports: [ 10130 ]

prometheus:
  enable: true
  ports: [20130]

friendVerify: false
groupMessageHasReadReceiptEnable: true
singleMessageHasReadReceiptEnable: true

