secret: openIM123
env: zookeeper
rpcRegisterName:
  user: user
  friend: friend
  msg: msg
  push: push
  messageGateway: messageGateway
  group: group
  auth: auth
  conversation: conversation
  third: third
imAdmin:
  userID: [ "imAdmin" ]
  nickname: [ "imAdmin" ]


