callback:
  url: "http://127.0.0.1:10008/callbackExample"
  beforeSendSingleMsg:
    enable: false
    timeout: 5
    failedContinue: true
  beforeUpdateUserInfoEx:
    enable:  false
    timeout: 5
    failedContinue: true
  afterUpdateUserInfoEx:
    enable:  false
    timeout: 5
    failedContinue: true
  afterSendSingleMsg:
    enable: false
    timeout: 5
    failedContinue: true
  beforeSendGroupMsg:
    enable: false
    timeout: 5
    failedContinue: true
  afterSendGroupMsg:
    enable: false
    timeout: 5
    failedContinue: true
  msgModify:
    enable: false
    timeout: 5
    failedContinue: true
  userOnline:
    enable: false
    timeout: 5
    failedContinue: true
  userOffline:
    enable: false
    timeout: 5
    failedContinue: true
  userKickOff:
    enable: false
    timeout: 5
    failedContinue: true
  offlinePush:
    enable: false
    timeout: 5
    failedContinue: true
  onlinePush:
    enable: false
    timeout: 5
    failedContinue: true
  superGroupOnlinePush:
    enable: false
    timeout: 5
    failedContinue: true
  beforeAddFriend:
    enable: false
    timeout: 5
    failedContinue: true
  beforeUpdateUserInfo:
    enable: false
    timeout: 5
    failedContinue: true
  beforeCreateGroup:
    enable: false
    timeout: 5
    failedContinue: true
  afterCreateGroup:
    enable: false
    timeout: 5
    failedContinue: true
  beforeMemberJoinGroup:
    enable: false
    timeout: 5
    failedContinue: true
  beforeSetGroupMemberInfo:
    enable: false
    timeout: 5
    failedContinue: true
  afterSetGroupMemberInfo:
    enable: false
    timeout: 5
    failedContinue: true
  setMessageReactionExtensions:
    enable: false
    timeout: 5
    failedContinue: true
  quitGroup:
    enable: false
    timeout: 5
    failedContinue: true
  killGroupMember:
    enable: false
    timeout: 5
    failedContinue: true
  dismissGroup:
    enable: false
    timeout: 5
    failedContinue: true
  joinGroup:
    enable: false
    timeout: 5
    failedContinue: true
  groupMsgRead:
    enable: false
    timeout: 5
    failedContinue: true
  singleMsgRead:
    enable: false
    timeout: 5
    failedContinue: true
  updateUserInfo:
    enable: false
    timeout: 5
    failedContinue: true
  beforeUserRegister:
    enable: false
    timeout: 5
    failedContinue: true
  afterUserRegister:
    enable: false
    timeout: 5
    failedContinue: true
  transferGroupOwner:
    enable: false
    timeout: 5
    failedContinue: true
  beforeSetFriendRemark:
    enable: false
    timeout: 5
    failedContinue: true
  afterSetFriendRemark:
    enable: false
    timeout: 5
    failedContinue: true
  afterGroupMsgRead:
    enable: false
    timeout: 5
    failedContinue: true
  afterGroupMsgRevoke:
    enable: false
    timeout: 5
    failedContinue: true
  afterJoinGroup:
    enable: false
    timeout: 5
    failedContinue: true
  beforeInviteUserToGroup:
    enable: false
    timeout: 5
    failedContinue: true
  joinGroupAfter:
    enable: false
    timeout: 5
    failedContinue: true
  setGroupInfoAfter:
    enable: false
    timeout: 5
    failedContinue: true
  setGroupInfoBefore:
    enable: false
    timeout: 5
    failedContinue: true
  revokeMsgAfter:
    enable: false
    timeout: 5
    failedContinue: true
  addBlackBefore:
    enable: false
    timeout: 5
    failedContinue: true
  addFriendAfter:
    enable: false
    timeout: 5
    failedContinue: true
  addFriendAgreeBefore:
    enable: false
    timeout: 5
    failedContinue: true
  deleteFriendAfter:
    enable: false
    timeout: 5
    failedContinue: true
  importFriendsBefore:
    enable: false
    timeout: 5
    failedContinue: true
  importFriendsAfter:
    enable: false
    timeout: 5
    failedContinue: true
  removeBlackAfter:
    enable: false
    timeout: 5
    failedContinue: true
